<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no" />
<meta name="author" content="Jiewei Qian, wacky6, Aries" />
<meta name="handheldfriendly" />
<link rel="stylesheet" href="/base.css">
<script src="/common.js"></script>
{%- block head  -%}
{%- endblock -%}
</head>
<body>
<div id="content_wrapper">
{%- block body -%}
{%- endblock -%}
</div>
<footer class="copyright">
  <a href="https://github.com/wacky6">jwQ, Aries, (C) 2014-2015, CC BY-NC-SA-4.0</a>
</footer>
</body>
</html>
